pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'us-east-1'
        TF_IN_AUTOMATION   = 'true'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir('week29/terraform') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('week29/terraform') {
                    sh 'terraform plan -out=tfplan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('week29/terraform') {
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }

        stage('Optional Destroy') {
            steps {
                dir('week29/terraform') {
                    script {
                        def destroyChoice = input(
                            message: 'Do you want to run terraform destroy?',
                            ok: 'Submit',
                            parameters: [
                                choice(
                                    name: 'DESTROY',
                                    choices: ['no', 'yes'],
                                    description: 'Select yes to destroy resources'
                                )
                            ]
                        )
                        if (destroyChoice == 'yes') {
                            sh 'terraform destroy -auto-approve'
                        } else {
                            echo "Skipping destroy"
                        }
                    }
                }
            }
        }
    }
}